### ISSUE TITLE
Seems desn't work in Sails 0.12.1

### ISSUE THREAD

**Issue by KSDaemon** [lykmapipo/sails-model-new#3]
Hi! 
Just made an npm install and tried to call User.new() in controller action (User is on of my model), but i'd got an error, that no new() is not a function, and it doesn't exists in model.
I don't know: am i doing smth wrong, or it really doesn't work.
Can you help me?

**Comment by bobbymanuel** [comment]
I'm getting the same error with 0.12.1.  +1 upvote on this issue - had to downgrade to 0.11.5.
"_()" lodash object wrapper doesn't seem to work anymore. the line _(sails.models).forEach(...) doesn't actually iterate.   just replace that usage with _.forEach(sails.models, function (model) {...}) in index.js and it works just fine.

**Comment by lykmapipo** [comment]
@bobbymanuel

I will appreciate a pull request fot the fix
